### ISSUE TITLE
Invalid Bucket Name

### ISSUE THREAD

**Issue by ilovefreesw** [microfeed/microfeed#8]
I followed all the steps carefully.

When I deployed it from GitHub Actions, it failed. I checked and there is an error in the Setup section
```
Error InvalidBucketName: The specified bucket name is not valid.
    at Request.extractError (/github/workspace/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/github/workspace/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/github/workspace/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/github/workspace/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/github/workspace/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/github/workspace/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /github/workspace/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/github/workspace/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/github/workspace/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/github/workspace/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidBucketName',
  region: null,
  time: 2022-12-28T06:50:02.829Z,
  requestId: null,
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 47.97243175497938
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Do I have to create a bucket first in R2 explicitly? because I didn't. I just crated ID And Secret as mentioned in the Readme.

**Comment by wenbinf** [comment]
the bucket name is derived from project name.

it's possible that your project name contains illegal characters that can't be used in a bucket name.

probably same issue as this:
https://github.com/microfeed/microfeed/issues/7

could you change the project name to contain only [a-z], [A-Z], [0-9], and -

please pay special attention to underscore character _, which is not allowed by cloudflare. 

TODO on our end: we should validate project name before actually deploying to cloudflare, so the error message can be more meaningful.

**Comment by ilovefreesw** [comment]
Sorry I shouldn't have opened an issue for it. I left a dot in the last part of the project name. My bad. I have fixed it now.
